datasource-mysql:
    validationQuery1: SELECT 1
    driverClassName1: com.mysql.jdbc.Driver
    type1: com.alibaba.druid.pool.DruidDataSource
    url1: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username1: root
    password1: 123456
    validationQuery2: SELECT 2
    driverClassName2: com.mysql.jdbc.Driver
    type2: com.alibaba.druid.pool.DruidDataSource
    url2: jdbc:mysql://localhost:3306/finalpro?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username2: root
    password2: 123456

dbPool:
    # 初始化大小，最小，最大
    initialSize: 10
    minIdle: 30
    maxActive: 100
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    exceptionSorter: true
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
